### ISSUE TITLE
Possible gpio-mvebu issue

### ISSUE THREAD

**Issue by tpetazzoni** [MISL-EBU-System-SW/mainline-public#52]
Evgeniy A. Dushistov reported an issue in the old plat-orion/gpio.c driver, and he claims the same issue applies to gpio-mvebu. This needs to be investigated, and potentially fixed.

See "Subject: [PATCH] fix for certain sequnce of request_irq can cause irq storm" on LAKML, from July, 26th 2014.

**Comment by gclement** [comment]
There was indeed a bug. A fix has been sent "[PATCH] gpio: mvebu: Fix mask/unmask managment per irq chip type" on linux-gpio@vger.kernel.org and linux-arm-kernel@lists.infradead.org mailing list.

**Comment by gclement** [comment]
Merged in with 61819549f572edd7fce53f228c0d8420cdc85f71
