### ISSUE TITLE
PCIE BAR registers are not configured to 64 bit address 

### ISSUE THREAD

**Issue by shrakrak** [MISL-EBU-System-SW/mainline-public#54]
according to PCI configuration space spec (http://wiki.osdev.org/PCI)
bits 1-2 of the BAR register define the size of the BAR address. 
0x0 - 32 bits
0x2 - 64 bits
in our driver we assume the BAR is 64 bits but we configure it as 32. since out DRAM is always at 0x0 by chance this doesnt cause any issue
see pci-mvebu.c :228 

also its worth checking the meaning of prefetchable bit (bit 3 of BAR register). we set it to 0x1 in our LSP. Maybe someone from the community can elaborate on that bit

**Comment by gclement** [comment]
According to the datasheet (I checked Armada XP and Armada 38x) bit 1-2 are read only and always equals to 0x2. So there is no need to setup it again in the driver. Maybe a comment could be added.
Same for bit 3, is it also read only and equal to 0x1.

**Comment by mv-star** [comment]
Hey Gregory

Indeed the value is set to 0x2 which means 2 bar registers should be used
per window and not one
If I remember correctly the driver uses a single bar register.
The register offset calculation assumes that, no?

**Comment by mv-star** [comment]
Also, I suspect the size bits are modifiable after all.

i clearly remember modifying them when i wrote a new u-boot driver for PCI-E

can you try and modify those bits ?

i suspect this might be a bug in the Spec

Yehuda

Hey Gregory

Indeed the value is set to 0x2 which means 2 bar registers should be used
per window and not one
If I remember correctly the driver uses a single bar register.
The register offset calculation assumes that, no?

**Comment by shrakrak** [comment]
The BAR are configure fine in regards to 64 bit addresses.
