### ISSUE TITLE
Fix i2c offloading

### ISSUE THREAD

**Issue by tpetazzoni** [MISL-EBU-System-SW/mainline-public#75]
As Antony Pavlov noticed, there is an unconditional "return false" at the beginning of the mv64xxx_i2c_can_offload() function which makes the offload mechanism never used. We need to remove it, and retest if the I2C works correctly.

**Comment by eranba** [comment]
Just removing the "return false" will probably won't be enough  to enable the offloading feature for certain devices(A38x, A39x etc), right ?
Seems like the "offload_enabled" flag should be set as well.

**Comment by tpetazzoni** [comment]
The offload_enabled flag is already set when the compatible string is marvell,mv78230-i2c.

The unconditional "return false" was removed as part of commit 0729a04977d497cf66234fd7f900ddcec3ef1c52, so this issue can be closed.
